### ISSUE TITLE
Russian Appstore

### ISSUE THREAD

**Issue by n0n1** [streamcloudapp/StreamCloud#98]
App not available for russian user in Appstore.

**Comment by yurijmi** [comment]
Strange. I downloaded it a month ago from Russian AppStore without any problems.

<img width="972" alt="2016-06-03 15 59 06" src="https://cloud.githubusercontent.com/assets/785492/15779301/96600b22-29ac-11e6-9531-c9438fd3cf42.png">

**Comment by plaetzchen** [comment]
We had a little downtime because I needed to renew my Apple Developer Account. Should be fixed now.
